### ISSUE TITLE
Timeout error message

### ISSUE THREAD

**Issue by Darkflame72** [vecnz/VerifyBot#12]
Add Timeout check so an error message can be displayed before the interaction times-out or delay the response to increase it to 15 minutes.

**Comment by BIOS9** [comment]
I am assuming you're talking about the slash command error where it errors if it tries to respond later than 3 seconds.
If so, I've fixed it in 29ee112c468b410246d5c4f39245947cf204b598 and you can close the issue.

If I've misunderstood the error you are talking about please let me know.
